version: '3.6'
services:

  glados-dgraph:
    image: dgraph/standalone:latest  # v21.03.1
    restart: always
    volumes:
      - dbdata:/dgraph
    networks: 
      - default
      - gladosnet
    ports:
      - 8080:8080
      - 9080:9080
      - 8000:8000

volumes:
  dbdata:

networks:
  gladosnet:
    external: true
